./script.sh source-bundler-1.X.X create-bundler-1.X.X-story update-bundler-1.X.X-bundler-cnb cloudfoundry/bundler-cnb
./script.sh source-bundler-2.X.X create-bundler-2.X.X-story update-bundler-2.X.X-bundler-cnb cloudfoundry/bundler-cnb
./script.sh source-dotnet-aspnetcore-2.1.X create-dotnet-aspnetcore-2.1.X-story update-dotnet-aspnetcore-2.1.X-dotnet-core-aspnet-cnb cloudfoundry/dotnet-core-aspnet-cnb
./script.sh source-dotnet-aspnetcore-2.2.X create-dotnet-aspnetcore-2.2.X-story update-dotnet-aspnetcore-2.2.X-dotnet-core-aspnet-cnb cloudfoundry/dotnet-core-aspnet-cnb
./script.sh source-dotnet-aspnetcore-3.0.X create-dotnet-aspnetcore-3.0.X-story update-dotnet-aspnetcore-3.0.X-dotnet-core-aspnet-cnb cloudfoundry/dotnet-core-aspnet-cnb
./script.sh source-dotnet-aspnetcore-3.1.X create-dotnet-aspnetcore-3.1.X-story update-dotnet-aspnetcore-3.1.X-dotnet-core-aspnet-cnb cloudfoundry/dotnet-core-aspnet-cnb
./script.sh source-dotnet-runtime-2.1.X create-dotnet-runtime-2.1.X-story update-dotnet-runtime-2.1.X-dotnet-core-runtime-cnb cloudfoundry/dotnet-core-runtime-cnb
./script.sh source-dotnet-runtime-2.2.X create-dotnet-runtime-2.2.X-story update-dotnet-runtime-2.2.X-dotnet-core-runtime-cnb cloudfoundry/dotnet-core-runtime-cnb
./script.sh source-dotnet-runtime-3.0.X create-dotnet-runtime-3.0.X-story update-dotnet-runtime-3.0.X-dotnet-core-runtime-cnb cloudfoundry/dotnet-core-runtime-cnb
./script.sh source-dotnet-runtime-3.1.X create-dotnet-runtime-3.1.X-story update-dotnet-runtime-3.1.X-dotnet-core-runtime-cnb cloudfoundry/dotnet-core-runtime-cnb
./script.sh source-dotnet-sdk-2.1.4X create-dotnet-sdk-2.1.4X-story update-dotnet-sdk-2.1.4X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.1.5X create-dotnet-sdk-2.1.5X-story update-dotnet-sdk-2.1.5X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.1.6X create-dotnet-sdk-2.1.6X-story update-dotnet-sdk-2.1.6X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.1.7X create-dotnet-sdk-2.1.7X-story update-dotnet-sdk-2.1.7X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.1.8X create-dotnet-sdk-2.1.8X-story update-dotnet-sdk-2.1.8X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.2.1X create-dotnet-sdk-2.2.1X-story update-dotnet-sdk-2.2.1X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.2.2X create-dotnet-sdk-2.2.2X-story update-dotnet-sdk-2.2.2X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.2.3X create-dotnet-sdk-2.2.3X-story update-dotnet-sdk-2.2.3X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-2.2.4X create-dotnet-sdk-2.2.4X-story update-dotnet-sdk-2.2.4X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-3.0.1X create-dotnet-sdk-3.0.1X-story update-dotnet-sdk-3.0.1X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-dotnet-sdk-3.1.1X create-dotnet-sdk-3.1.1X-story update-dotnet-sdk-3.1.1X-dotnet-core-sdk-cnb cloudfoundry/dotnet-core-sdk-cnb
./script.sh source-go-1.12.X create-go-1.12.X-story update-go-1.12.X-go-compiler-cnb cloudfoundry/go-compiler-cnb
./script.sh source-go-1.13.X create-go-1.13.X-story update-go-1.13.X-go-compiler-cnb cloudfoundry/go-compiler-cnb
./script.sh source-nginx-1.16.X create-nginx-1.16.X-story update-nginx-1.16.X-nginx-cnb cloudfoundry/nginx-cnb
./script.sh source-nginx-1.17.X create-nginx-1.17.X-story update-nginx-1.17.X-nginx-cnb cloudfoundry/nginx-cnb
./script.sh source-node-10.X.X create-node-10.X.X-story update-nginx-1.17.X-nginx-cnb cloudfoundry/nginx-cnb
./script.sh source-node-12.X.X create-node-12.X.X-story update-node-10.X.X-node-engine-cnb cloudfoundry/node-engine-cnb
./script.sh source-node-13.X.X create-node-13.X.X-story update-node-12.X.X-node-engine-cnb cloudfoundry/node-engine-cnb
./script.sh source-node-8.X.X create-node-8.X.X-storyupdate-node-8.X.X-node-engine-cnb cloudfoundry/node-engine-cnb
./script.sh source-php-7.2.X create-php-7.2.X-story update-php-7.2.X-php-dist-cnb cloudfoundry/php-dist-cnb
./script.sh source-php-7.3.X create-php-7.3.X-story update-php-7.3.X-php-dist-cnb cloudfoundry/php-dist-cnb
./script.sh source-php-7.4.X create-php-7.4.X-story update-php-7.4.X-php-dist-cnb cloudfoundry/php-dist-cnb
./script.sh source-python-2.7.X create-python-2.7.X-story update-python-2.7.X-python-runtime-cnb cloudfoundry/python-runtime-cnb
./script.sh source-python-3.5.X create-python-3.5.X-story update-python-3.5.X-python-runtime-cnb cloudfoundry/python-runtime-cnb
./script.sh source-python-3.6.X create-python-3.6.X-story update-python-3.6.X-python-runtime-cnb cloudfoundry/python-runtime-cnb
./script.sh source-python-3.7.X create-python-3.7.X-story update-python-3.7.X-python-runtime-cnb cloudfoundry/python-runtime-cnb
./script.sh source-python-3.8.X create-python-3.8.X-story update-python-3.8.X-python-runtime-cnb cloudfoundry/python-runtime-cnb
./script.sh source-ruby-2.4.X create-ruby-2.4.X-story update-ruby-2.4.X-ruby-cnb cloudfoundry/ruby-cnb
./script.sh source-ruby-2.5.X create-ruby-2.5.X-story update-ruby-2.5.X-ruby-cnb cloudfoundry/ruby-cnb
./script.sh source-ruby-2.6.X create-ruby-2.6.X-story update-ruby-2.6.X-ruby-cnb cloudfoundry/ruby-cnb
